### PR TITLE
Remove excessive is visible check, support Jest testing enviroment

### LINKED ISSUE #1426: Support use of Swal in Jest testing environment
## New feature motivation

A few days ago I was working on https://github.com/sweetalert2/sweetalert2-react-content/pull/72, and when I left it, the last commit (https://github.com/sweetalert2/sweetalert2-react-content/pull/72/commits/33fe8d658e48c466325e77dde8b33488519c8cfc) had passing tests.

When I came back to it a couple days later, the same commit had failing tests due to the v8.2.3 patch release. 

I managed to reproduce the bug in the [swal-not-resolve-in-jest-bug repo](https://github.com/sweetalert2/swal-not-resolve-in-jest-bug). You can see that [the build for the `master` branch](https://travis-ci.org/sweetalert2/swal-not-resolve-in-jest-bug/builds/497823672) (using sweetalert v8.2.2) is passing, but [the build for the `upgrade-sweetalert2-to-v8.2.3` branch](https://travis-ci.org/sweetalert2/swal-not-resolve-in-jest-bug/builds/497824375) is failing, due to the `swal` instance never resolving. (No idea why to be honest.. at first glance, [the changes from v8.2.2 to v8.2.3](https://github.com/sweetalert2/sweetalert2/compare/v8.2.2...v8.2.3) don't seem like they would cause this kind of problem)

Jest is an incredible testing tool, and it would be nice if sweetalert2 was supported [consistently] in this environment.

## New feature 

I propose to add first-class support for Jest, by doing the following things:
1. Add `check:jest` to the package scripts, with only one or two very basic tests, as "smoke testing" for the Jest environment. Fine-grained testing of functionality should continue to happen *only* in the existing karma+qunit test environment.
2. Debug and fix the above mentioned problem (reproduced in https://github.com/sweetalert2/swal-not-resolve-in-jest-bug).
3. Not strictly needed, but would make testing in Jest nicer: Check for existence of `window.scrollTo` before calling it, to avoid the need to mock it here: https://github.com/sweetalert2/swal-not-resolve-in-jest-bug/blob/f06bbd41dc51716810cd274e5e4efa7e581d5383/test.js#L4-L7

### PR DESCRIPTION
**Pull request by limonte**
Fixes #1426

With the help of https://github.com/facebook/jest/issues/8062 I figured out that:

- `elem.offsetWidth` and similar are always `0`
- `isVisible()` always returns `false`
- `if (targetedConfirm && constructor.isVisible()) {` will never be `true` 
- confirm button never got clicked in https://github.com/sweetalert2/swal-not-resolve-in-jest-bug/blob/master/test.js#L18
- swal never resolves

~I think that those checks are legacy and not needed anymore.~ (my mistake, thanks @gverni!)

### CODE REVIEW

**Comment by gverni** [comment]
Hi @limonte if you are not in a hurry, could you give me few hours to review these changes?

File: src/instanceMethods/_main.js [hunk 1]
```diff
@@ -120,7 +120,7 @@ export function _main (userParams) {
       switch (e.type) {
         case 'click':
           // Clicked 'confirm'
-          if (targetedConfirm && constructor.isVisible()) {
```
Comment (gverni) [inline src/instanceMethods/_main.js]: I'm just reluctant in removing this check. Maybe I'm too scrupulous but there may be race conditions where the click event come when the constructor is _available_ but not visible. 

I tried to simulate a race condition in branch https://github.com/sweetalert2/sweetalert2/tree/fix/remove-excessive-isVisible-check-race-condition. I know that this example is quite stupid and probably doesn't represent a real use case but it shows the kind of unexpected behaviors I'm worried about. 

Having said that, probably the benefit of this change outweighs the risks, and I haven't followed the discussion on jest to closely to be able to judge the benefit. So feel free to ignore the comment...

Comment (limonte) [reply src/instanceMethods/_main.js]: Am I doing something wrong or `remove-excessive-isVisible-check` and `remove-excessive-isVisible-check-race-condition` branches are identical?

Comment (limonte) [reply src/instanceMethods/_main.js]: Alright, now I see that 

```js
Swal.close()
Swal.clickConfirm()
```

produces an error.

Will handle that case and cover it by test 👍

Comment (gverni) [reply src/instanceMethods/_main.js]: Sorry, I forgot to commit my test (aaarg.. https://twitter.com/hashtag/NoDeploymentFridays?src=hash). It's on the branch now...

**Comment by zenflow** [comment]
> Also, as @zenflow suggested, to fully support Jest and prevent devs from a need to mock window.scrollTo, added a check for its existence before usage

I saw this in the original PR comment, but it was removed. Did you change your mind about this @limonte ? I don't think it's a big deal either way (since it's easy to discover what the problem is and work around it) but it would be nice if Swal was able to run in Jest without modifying the environment

File: src/instanceMethods/_main.js (hunk 1 above)
Comment (limonte) [reply src/instanceMethods/_main.js]: @gverni I think this case should be handled by https://github.com/sweetalert2/sweetalert2/pull/1439/commits/9748d7b6e045adf4178983c6bdca412d843fcb99

Please review, thanks!

**Comment by limonte** [comment]
> I saw this in the original PR comment, but it was removed. Did you change your mind about this @limonte ? 

I would like to get it done, but see what's happening here. I just added the `[WIP]` commit with the change: https://github.com/sweetalert2/sweetalert2/pull/1439/commits/f1b83c73591f5a65e1fcbe495fb6a0be1a86aa71?w=1

But Jest is still complaining (it's a warning, not an error) about window.scrollTo is not implemented: https://travis-ci.org/sweetalert2/sweetalert2/builds/503950441

image

**Comment by SimenB** [comment]
Jsdom throws on access, not usage

**Comment by limonte** [comment]
> Jsdom throws on access, not usage

Thank you for tracking this issue and helping us @SimenB! Do I understand correctly that there's no way to check `window.scrollTo` on SweetAlert2's side because checking means "access"? In other words devs will always need to have something like 

```js
beforeAll(() => {
  // jest doesn't implement `window.scrollTo` so we need to mock it
  window.scrollTo = () => {}
})
```

in their `test.js` files if they're dealing with SweetAlert2?

**Comment by SimenB** [comment]
Yeah, I think so. At least without a try-catch or something. I'd just stick it in your docs if you wanna do anything

**Comment by limonte** [comment]
@zenflow @gverni the PR is ready for review 🚀
