### PR TITLE
Fix complexity of close method

### LINKED ISSUE #1531: Fix "method_complexity" issue in src/instanceMethods/close.js
Function `close` has a Cognitive Complexity of 7 (exceeds 5 allowed). Consider refactoring.

https://codeclimate.com/github/sweetalert2/sweetalert2/src/instanceMethods/close.js#issue_5cae1f5bcb82c9000100006f

### PR DESCRIPTION
**Pull request by JulianoGTZ**
Separate some responsibilities relative to animation on the close method.

Fixes #1531

### CODE REVIEW

File: src/instanceMethods/close.js [hunk 1]
```diff
@@ -70,23 +70,11 @@ export function close (resolveValue) {
 
   const innerParams = privateProps.innerParams.get(this)
   const swalPromiseResolve = privateMethods.swalPromiseResolve.get(this)
-  const onClose = innerParams.onClose
-  const onAfterClose = innerParams.onAfterClose
+  const { onClose } = innerParams
 
-  dom.removeClass(popup, swalClasses.show)
-  dom.addClass(popup, swalClasses.hide)
+  replacePopupClass({ popup })
```
Comment (limonte) [inline src/instanceMethods/close.js]: The choice of the name for the function isn't the best, do we need this function at all? I think codeclimate will be happy even without introducing `replacePopupClass()`

File: src/instanceMethods/close.js [hunk 2]
```diff
@@ -99,6 +87,32 @@ export function close (resolveValue) {
   delete this.params
 }
 
+const handlePopupAnimation = ({ popup, innerParams : { onAfterClose } }) => {
+  const container = dom.getContainer()
+  // If animation is supported, animate
+  const animationIsSupported = dom.animationEndEvent && dom.hasCssAnimation(popup);
+
+  if (animationIsSupported) {
+    animatePopup({ popup, container, onAfterClose })
```
Comment (limonte) [inline src/instanceMethods/close.js]: what's the deal with passing one object instead of multiple params into aa function?

File: src/instanceMethods/close.js [hunk 3]
```diff
@@ -99,6 +87,32 @@ export function close (resolveValue) {
   delete this.params
 }
 
+const handlePopupAnimation = ({ popup, innerParams : { onAfterClose } }) => {
```
Comment (limonte) [inline src/instanceMethods/close.js]: > `{ popup, innerParams : { onAfterClose } }`

I have hard time readng this :) Can we simplify it to `handlePopupAnimation = (popup, onAfterClose) => {`?

File: src/instanceMethods/close.js (hunk 1 above)
Comment (JulianoGTZ) [reply src/instanceMethods/close.js]: really did not need to. It worked fine without the function.

File: src/instanceMethods/close.js (hunk 2 above)
Comment (JulianoGTZ) [reply src/instanceMethods/close.js]: I relied on this [repository](https://github.com/ryanmcdermott/clean-code-javascript#functions), with some clean code tips. Where I currently work, restructuring in this way has helped to give more readability in calling functions

File: src/instanceMethods/close.js (hunk 3 above)
Comment (JulianoGTZ) [reply src/instanceMethods/close.js]: yes. Reading again...it's not clear that param is the After Close.

File: src/instanceMethods/close.js (hunk 2 above)
Comment (limonte) [reply src/instanceMethods/close.js]: Sorry for the delayed reply @JulianoGTZ and thanks for linking the `clean-code-javascript` repo, it's very useful!

While I agree on the example in the repo, I disagree that using that technique improves readability in this PR. Let me explain on examples:

---

The example from the `clean-code-javascript` repo:

```js
// with object
function createMenu({ title, body, buttonText, cancellable }) { ... }
createMenu({
  title: "Foo",
  body: "Bar",
  buttonText: "Baz",
  cancellable: true
});

// without object
function createMenu(title, body, buttonText, cancellable) { ... }
createMenu({
  "Foo",
  "Bar",
  "Baz",
  true
});
```

Clearly, using the object is way better in terms of readability.

---

In our case:

```js
// with object
const animatePopup = ({ popup, container, onAfterClose }) => { ... }
animatePopup({ popup, container, onAfterClose })

// without object
const animatePopup = (popup, container, onAfterClose) => { ... }
animatePopup(popup, container, onAfterClose)
```

Almost no difference in terms of readability, in fact the first one (with object) is a bit harder to read.

So, if you're okay, let's not introduce objects in this PR.

Comment (JulianoGTZ) [reply src/instanceMethods/close.js]: hi @limonte. I agree totally, especially with the example.

Apart from contributing to the community and with this repository, I expected to obtain this type of learning.

Really, thank you very much.

**Comment by gverni** [comment]
Thanks @JulianoGTZ for your help! For the future you may want to install some plugin in your IDE for highlighting linting/formatting errors. I've found few empty lines an extra spaces scattered around your code. I personally use [StandardJS](https://standardjs.com/) and its [VSC plugin](https://marketplace.visualstudio.com/items/chenxsan.vscode-standardjs). 

@limonte I'm going to adjust those in my next PR to fix #1640

**Comment by limonte** [comment]
As per email agreement with @JulianoGTZ I just sent the invitation to become SweetAlert2's collaborator. Welcome aboard @JulianoGTZ :beers: 

Also, @gverni I granted you the owner permissions to the org, if a bus-factor will happen to me, I believe you'll not allow SweetAlert2 to fade away.

---

As to formatting rules, we should add those rules about spaces to our eslint config to enforce the coding style. @gverni I believe this one is what you're talking about https://eslint.org/docs/rules/space-in-parens

**Comment by limonte** [comment]
> As to formatting rules, we should add those rules about spaces to our eslint config to enforce the coding style. @gverni I believe this one is what you're talking about https://eslint.org/docs/rules/space-in-parens

Done: https://github.com/sweetalert2/sweetalert2/commit/60dd1e7634fecb23d397041fab8fab3b37ed75f4 

cc @gverni

**Comment by gverni** [comment]
> Done in 80e04f0

Thanks @limonte! It was exactly that...

> Also, @gverni I granted you the owner permissions to the org, if a bus-factor will happen to me, I believe you'll not allow SweetAlert2 to fade away.

I'm honored @limonte, thank you so much! I love this project, and I'll do my best! But be careful with 🚌 out there 😄

**Comment by gverni** [comment]
> we should add those rules about spaces to our eslint config to enforce the coding style

@limonte, how about adding also: 
* [`padded-block`](https://eslint.org/docs/rules/padded-blocks)
* [`no-multi-spaces`](https://eslint.org/docs/rules/no-multi-spaces#disallow-multiple-spaces-no-multi-spaces)

I'm taking inspiration from https://github.com/standard/eslint-config-standard. We can also merge more settings from there (where we see fit). Let me know if you are in favor and I can open a PR for that.

**Comment by limonte** [comment]
> I'm taking inspiration from https://github.com/standard/eslint-config-standard. We can also merge more settings from there (where we see fit). Let me know if you are in favor and I can open a PR for that.

Why not to extend it then instead of copy-pasting rules? #1643
