### PR TITLE
Fix/require in node env

### LINKED ISSUE #996: "document is not defined" - server side rendering broke from version 7.13.1 to 7.13.2
Hi, all.

From version 7.13.2 onwards, merely importing `swal` breaks node environments with "document is not defined".

I tried to find here what could have caused this to come up with a PR, but I couldn't find anything strange. Sorry :/

https://github.com/sweetalert2/sweetalert2/compare/v7.13.1...v7.13.2

### PR DESCRIPTION
**Pull request by zenflow**
Related to #996

This branch just adds a (currently failing) check to the `npm test` script to ensure you can `require('sweetalert2')` without crashing. (And fixes the semantics of our npm script for qunit tests.)

Once tests-always-included/gulp-css2js#6 is merged we just have to rerun the build from the Travis site and it should pass (assuming the change is published as a minor or patch release).

Then we can merge and make a patch release to close #996

### CODE REVIEW

**Comment by limonte** [comment]
Sometimes I feel stupid :) I made the whole repo for the same purpose: https://github.com/sweetalert2/sweetalert2-adonisjs-nuxtjs

And then @zenflow is coming with 3 LoC simple and obvious (not for me, apparently) solution :)

File: gulpfile.js [hunk 1]
```diff
@@ -75,9 +75,13 @@ gulp.task('build:styles', () => {
  * Warning: This task depends on dist/sweetalert2.js & dist/sweetalert2.css
  */
 gulp.task('build:standalone', () => {
+  const css2jsOptions = {
```
Comment (limonte) [inline gulpfile.js]: nice :+1:
