### PR TITLE
Fix openPopup method complexity

### LINKED ISSUE #1530: Fix "method_complexity" issue in src/utils/openPopup.js
Function `openPopup` has a Cognitive Complexity of 12 (exceeds 5 allowed). Consider refactoring.

https://codeclimate.com/github/sweetalert2/sweetalert2/src/utils/openPopup.js#issue_5cae1f5bcb82c9000100006d

### PR DESCRIPTION
**Pull request by kwdowik**
Fixes #1530

### CODE REVIEW

File: src/utils/openPopup.js [hunk 1]
```diff
@@ -20,48 +20,60 @@ export const openPopup = (params) => {
...
+  if (typeof params.onBeforeOpen === 'function') {
     params.onBeforeOpen(popup)
   }
 
-  if (params.animation) {
-    dom.addClass(popup, swalClasses.show)
-    dom.addClass(container, swalClasses.fade)
-  }
-  dom.show(popup)
+  addClasses({ container, popup })(params)
```
Comment (limonte) [inline src/utils/openPopup.js]: What's the deal with functions returning functions? For me personally, it's quite hard to read such code, is it possible to achieve the same result with "simple" functions?

Robots (codeclimate) are happy with the code, but we should have humans in mind as well :)

File: src/utils/openPopup.js [hunk 2]
```diff
@@ -20,48 +20,60 @@ export const openPopup = (params) => {
...
 
   // scrolling is 'hidden' until animation is done, after that 'auto'
+  setScrollingVisibility({ container, popup })
```
Comment (limonte) [inline src/utils/openPopup.js]: please use the list of arguments instead of the object of arguments, the same as in https://github.com/sweetalert2/sweetalert2/pull/1641#discussion_r300373805

File: src/utils/openPopup.js (hunk 1 above)
Comment (kwdowik) [reply src/utils/openPopup.js]: Yeah, of course. A higher-order function is not necessary here, I will change this.

File: src/utils/openPopup.js (hunk 2 above)
Comment (kwdowik) [reply src/utils/openPopup.js]: You are right, I will do that
